menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: "/archives"
      weight: 30

params:
  profileMode:
    enabled: true
    title: "Hey Hey!" # optional default will be site title
    subtitle: "Glad to see ya around!"
    imageUrl: "images/T3PFP.png" # optional
    imageTitle: "T3PFP" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archives
        url: "/archives"
      - name: Repo source!
        url: "https://github.com/T342guy/t342.dev"

  socialIcons: # optional
    - name: "Steam"
      url: "https://steamcommunity.com/id/T342guy/"
    - name: "Github"
      url: "https://github.com/T342guy"