menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: posts
      name: Posts
      url: "/posts"
      weight: 30
    - identifier: backtohome
      name: Back to home
      url: "/"
      weight: 40

params:
  profileMode:
    enabled: true
    title: "Hey Hey!" # optional default will be site title
    subtitle: "Glad to see ya around my profile!"
    imageUrl: "https://i.postimg.cc/wTcrp28N/512pfp.png" # optional
    imageTitle: "T3PFP" # optional
    imageWidth: 320 # custom size
    imageHeight: 320 # custom size
    buttons:
      - name: Posts
        url: "/posts"

  socialIcons: # optional
    - name: "Steam"
      url: "https://steamcommunity.com/id/T342guy/"
    - name: "Github"
      url: "https://github.com/T342guy"
    - name: "Twitch"
      url: "https://www.twitch.tv/t342guy"
    - name: "Youtube"
      url: "https://www.youtube.com/@T342guy"
    - name: "Twitter"
      url: "https://x.com/T342guy"
    - name: "Bluesky"
      url: "https://bsky.app/profile/t342.dev"
    - name: "medal.gg"
      url: "https://medal.tv/u/T342/?invite=ur-MSxSbk0sMzIwMDQ3Nzg2"
    - name: "itchio"
      url: "https://t342guy.itch.io/"