menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

params:
  homeInfoParams:
    Title: Hey hey! wave
    Content: Glad to see ya around! 

  socialIcons: # optional
    - name: "Steam"
      url: "https://steamcommunity.com/id/T342guy/"
    - name: "Github"
      url: "https://github.com/T342guy"